/**
 * Canonical API error codes. The backend always responds with { code, message, fields? }.
 * The frontend maps these codes to UX behaviour (toast, redirect, upgrade prompt...).
 */
export const ErrorCodes = {
  // auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REUSED: 'TOKEN_REUSED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  // authorization
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  TENANT_CONTEXT_REQUIRED: 'TENANT_CONTEXT_REQUIRED',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  MEMBERSHIP_INACTIVE: 'MEMBERSHIP_INACTIVE',
  SOCIETY_SUSPENDED: 'SOCIETY_SUSPENDED',
  // modules / plans / subscriptions
  MODULE_DISABLED: 'MODULE_DISABLED',
  MODULE_NOT_IN_PLAN: 'MODULE_NOT_IN_PLAN',
  MODULE_INACTIVE: 'MODULE_INACTIVE',
  MODULE_DEPENDENCY_MISSING: 'MODULE_DEPENDENCY_MISSING',
  MODULE_CORE_LOCKED: 'MODULE_CORE_LOCKED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_SUSPENDED: 'SUBSCRIPTION_SUSPENDED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',
  SUBSCRIPTION_READ_ONLY: 'SUBSCRIPTION_READ_ONLY',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  PLAN_UNAVAILABLE: 'PLAN_UNAVAILABLE',
  // generic
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  // domain
  LAST_ADMIN_PROTECTED: 'LAST_ADMIN_PROTECTED',
  SYSTEM_ROLE_PROTECTED: 'SYSTEM_ROLE_PROTECTED',
  SELF_ACTION_NOT_ALLOWED: 'SELF_ACTION_NOT_ALLOWED',
  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PASS_INVALID: 'PASS_INVALID',
  PASS_EXPIRED: 'PASS_EXPIRED',
  PASS_REVOKED: 'PASS_REVOKED',
  PASS_WRONG_SOCIETY: 'PASS_WRONG_SOCIETY',
  JOURNAL_UNBALANCED: 'JOURNAL_UNBALANCED',
  IMPORT_NOT_VALIDATED: 'IMPORT_NOT_VALIDATED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DUPLICATE_VOTE: 'DUPLICATE_VOTE',
  OUTSTANDING_DUES: 'OUTSTANDING_DUES',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorBody {
  code: ErrorCode | string;
  message: string;
  fields?: Record<string, string[]>;
  details?: Record<string, unknown>;
  requestId?: string;
}
