import { Badge, type BadgeProps } from '@/components/ui/badge';
import { formatStatus } from '@/lib/utils';

const TONES: Record<string, BadgeProps['variant']> = {
  ACTIVE: 'success',
  PAID: 'success',
  APPROVED: 'success',
  RESOLVED: 'success',
  CONFIRMED: 'success',
  COMPLETED: 'success',
  CHECKED_IN: 'success',
  SUCCESS: 'success',
  PUBLISHED: 'success',
  PRESENT: 'success',
  CONVERTED: 'success',
  OPEN: 'info',
  ISSUED: 'info',
  NEW: 'info',
  TRIALING: 'info',
  IN_PROGRESS: 'info',
  PENDING: 'warning',
  PENDING_APPROVAL: 'warning',
  PENDING_PAYMENT: 'warning',
  PARTIALLY_PAID: 'warning',
  PAST_DUE: 'warning',
  WAITING: 'warning',
  DRAFT: 'muted',
  INACTIVE: 'muted',
  ARCHIVED: 'muted',
  CLOSED: 'muted',
  CHECKED_OUT: 'muted',
  MOVED_OUT: 'muted',
  VACANT: 'muted',
  EXPIRED: 'destructive',
  OVERDUE: 'destructive',
  SUSPENDED: 'destructive',
  CANCELLED: 'destructive',
  REJECTED: 'destructive',
  DENIED: 'destructive',
  FAILED: 'destructive',
  CRITICAL: 'destructive',
  HIGH: 'warning',
  NORMAL: 'secondary',
  LOW: 'muted',
  REOPENED: 'warning',
  INVESTIGATING: 'info',
  ACKNOWLEDGED: 'info',
  FALSE_ALARM: 'muted',
  MEDIUM: 'info',
  ESCALATED: 'destructive',
  RENEWED: 'muted',
  TERMINATED: 'destructive',
  PURCHASED: 'info',
  LOCKED: 'destructive',
  INVITED: 'info',
  ACCEPTED: 'success',
  REVOKED: 'muted',
  BETA: 'info',
  UNDER_MAINTENANCE: 'warning',
  DISPOSED: 'muted',
  OWNER_OCCUPIED: 'success',
  TENANT_OCCUPIED: 'info',
  REFUNDED: 'muted',
  CREATED: 'info',
  PROCESSED: 'success',
  IGNORED: 'muted',
  DUPLICATE: 'muted',
  UNPAID: 'warning',
  PARTIAL: 'warning',
};

export function StatusBadge({ status, label, className }: { status: string | null | undefined; label?: string; className?: string }) {
  if (!status) return <Badge variant="muted" className={className}>—</Badge>;
  return (
    <Badge variant={TONES[status] ?? 'secondary'} className={className}>
      {label ?? formatStatus(status)}
    </Badge>
  );
}
