import type { RoleLanding } from '../constants/enums';

export interface DefaultRoleDefinition {
  key: string;
  name: string;
  description: string;
  landing: RoleLanding;
  /** when true the role automatically holds every permission of every module the society can access */
  grantsAllPermissions: boolean;
  permissions: string[];
  /** system roles cannot be deleted, only customised */
  isSystem: boolean;
  color: string;
}

/**
 * DEFAULT society roles created for every new society. They are a starting point only:
 * Society Admins can edit them and create unlimited custom roles. Runtime source of truth is the DB.
 */
export const DEFAULT_SOCIETY_ROLES: DefaultRoleDefinition[] = [
  {
    key: 'SOCIETY_ADMIN',
    name: 'Society Admin',
    description: 'Full access to every module included in the current plan.',
    landing: 'ADMIN',
    grantsAllPermissions: true,
    permissions: [],
    isSystem: true,
    color: 'violet',
  },
  {
    key: 'COMMITTEE',
    name: 'Committee Member',
    description: 'Operational oversight: complaints, notices, visitors, amenities, approvals, meetings and reports.',
    landing: 'ADMIN',
    grantsAllPermissions: false,
    isSystem: true,
    color: 'blue',
    permissions: [
      'dashboard:view',
      'society:view',
      'society:view_audit',
      'society:view_subscription',
      'units:view',
      'units:export',
      'residents:view',
      'residents:view_contact',
      'residents:lookup',
      'residents:export',
      'residents:approve_move',
      'vehicles:view',
      'parking:view',
      'billing:view',
      'billing:export',
      'payments:view',
      'payments:export',
      'expenses:view',
      'expenses:approve',
      'expenses:export',
      'accounting:view',
      'accounting:export',
      'complaints:view',
      'complaints:create',
      'complaints:update',
      'complaints:assign',
      'complaints:resolve',
      'complaints:close',
      'complaints:comment',
      'complaints:export',
      'visitors:view',
      'visitors:export',
      'delivery:view',
      'security:view',
      'security:update',
      'security:resolve',
      'amenities:view',
      'amenities:view_bookings',
      'amenities:approve',
      'amenities:cancel',
      'amenities:book',
      'amenities:view_own',
      'staff:view',
      'staff:attendance',
      'domestic_help:view',
      'domestic_help:verify',
      'vendors:view',
      'contracts:view',
      'assets:view',
      'inventory:view',
      'notices:view',
      'notices:create',
      'notices:update',
      'notices:publish',
      'communication:view',
      'communication:create',
      'communication:moderate',
      'communication:announce',
      'events:view',
      'events:create',
      'events:update',
      'events:rsvp',
      'polls:view',
      'polls:create',
      'polls:update',
      'polls:vote',
      'polls:results',
      'surveys:view',
      'surveys:create',
      'surveys:update',
      'surveys:respond',
      'surveys:results',
      'meetings:view',
      'meetings:create',
      'meetings:update',
      'meetings:minutes',
      'voting:view',
      'voting:create',
      'voting:vote',
      'voting:results',
      'voting:close',
      'governance:view',
      'documents:view',
      'documents:create',
      'documents:download',
      'documents:view_own',
      'reports:view',
      'emergency:view',
      'emergency:respond',
      'emergency:broadcast',
      'support:create',
      'support:view_own',
      'support:view',
      'notifications:view',
    ],
  },
  {
    key: 'STAFF',
    name: 'Staff',
    description: 'Facility staff: work on assigned complaints, maintain assets and inventory.',
    landing: 'ADMIN',
    grantsAllPermissions: false,
    isSystem: true,
    color: 'amber',
    permissions: [
      'dashboard:view',
      'complaints:view',
      'complaints:update',
      'complaints:resolve',
      'complaints:comment',
      'assets:view',
      'assets:maintain',
      'inventory:view',
      'inventory:transact',
      'visitors:view',
      'notices:view',
      'events:view',
      'support:create',
      'support:view_own',
      'notifications:view',
    ],
  },
  {
    key: 'SECURITY_GUARD',
    name: 'Security Guard',
    description: 'Gate operations only: visitor passes, walk-ins, deliveries, incidents.',
    landing: 'GUARD',
    grantsAllPermissions: false,
    isSystem: true,
    color: 'emerald',
    permissions: [
      'visitors:view',
      'visitors:create',
      'visitors:checkin',
      'visitors:checkout',
      'delivery:view',
      'delivery:create',
      'delivery:update',
      'delivery:collect',
      'residents:lookup',
      'vehicles:view',
      'domestic_help:view',
      'security:view',
      'security:create',
      'emergency:view',
      'emergency:sos',
      'emergency:respond',
      'notifications:view',
    ],
  },
  {
    key: 'MEMBER',
    name: 'Member',
    description: 'Resident self-service: own unit, bills, payments, complaints, visitors, amenities and community.',
    landing: 'MEMBER',
    grantsAllPermissions: false,
    isSystem: true,
    color: 'slate',
    permissions: [
      'dashboard:view',
      'residents:view_own',
      'residents:manage_own',
      'billing:view_own',
      'payments:view_own',
      'payments:pay_own',
      'complaints:view_own',
      'complaints:create',
      'complaints:comment',
      'visitors:view_own',
      'visitors:create_own',
      'delivery:view_own',
      'delivery:create_own',
      'vehicles:view_own',
      'vehicles:create_own',
      'domestic_help:view_own',
      'domestic_help:create_own',
      'amenities:view',
      'amenities:book',
      'amenities:view_own',
      'documents:view_own',
      'notices:view',
      'communication:view',
      'communication:create',
      'events:view',
      'events:rsvp',
      'polls:view',
      'polls:vote',
      'surveys:view',
      'surveys:respond',
      'meetings:view',
      'voting:view',
      'voting:vote',
      'emergency:view',
      'emergency:sos',
      'support:create',
      'support:view_own',
      'notifications:view',
    ],
  },
];

export const PLATFORM_ROLES: DefaultRoleDefinition[] = [
  {
    key: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Controls the SaaS platform.',
    landing: 'PLATFORM',
    grantsAllPermissions: true,
    permissions: [],
    isSystem: true,
    color: 'rose',
  },
];
