import type { ModuleDefinition, ModuleActionDefinition, NavigationItemDefinition } from './types';

const a = (key: string, label: string): ModuleActionDefinition => ({ key, label });

const nav = (
  key: string,
  group: string,
  label: string,
  path: string,
  permissions: string[],
  sortOrder: number,
  icon?: string,
): NavigationItemDefinition => ({ key, group, label, path, permissions, sortOrder, audience: 'PLATFORM', icon });

const platform = (
  key: string,
  name: string,
  description: string,
  icon: string,
  sortOrder: number,
  actions: ModuleActionDefinition[],
  navigation: NavigationItemDefinition[],
): ModuleDefinition => ({
  key,
  name,
  description,
  icon,
  category: 'PLATFORM',
  scope: 'PLATFORM',
  isCore: true,
  status: 'ACTIVE',
  sortOrder,
  dependencies: [],
  actions,
  navigation,
  version: '1.0.0',
  configuration: {},
});

/** Platform (SaaS owner) modules. Access is granted through platform roles such as SUPER_ADMIN. */
export const PLATFORM_MODULES: ModuleDefinition[] = [
  platform('platform_dashboard', 'Platform Overview', 'SaaS KPIs: societies, MRR, ARR, expiry, leads, support.', 'LayoutDashboard', 0, [a('view', 'View platform dashboard')], [
    nav('overview', 'overview', 'Overview', '/admin', ['platform_dashboard:view'], 0, 'LayoutDashboard'),
  ]),
  platform(
    'platform_societies',
    'Societies',
    'Tenant directory, society detail, suspension and society-level module control.',
    'Building2',
    1,
    [
      a('view', 'View societies'),
      a('create', 'Create societies'),
      a('update', 'Update societies'),
      a('suspend', 'Suspend / reactivate societies'),
      a('delete', 'Archive societies'),
      a('manage_modules', 'Manage society modules'),
      a('view_users', 'View society users'),
      a('manage_admins', 'Reset society admin access'),
      a('view_usage', 'View usage & limits'),
    ],
    [nav('societies', 'saas', 'Societies', '/admin/societies', ['platform_societies:view'], 0, 'Building2')],
  ),
  platform(
    'platform_subscriptions',
    'Subscriptions',
    'Subscription lifecycle, expiry radar, extensions and plan changes.',
    'CreditCard',
    2,
    [
      a('view', 'View subscriptions'),
      a('update', 'Update subscriptions'),
      a('extend', 'Extend subscriptions'),
      a('change_plan', 'Change plan'),
      a('cancel', 'Cancel / suspend subscriptions'),
      a('remind', 'Send renewal reminders'),
    ],
    [
      nav('subscriptions', 'saas', 'Subscriptions', '/admin/subscriptions', ['platform_subscriptions:view'], 1, 'CreditCard'),
      nav('expiry', 'saas', 'Expiry Radar', '/admin/subscriptions/expiry', ['platform_subscriptions:view'], 2, 'Radar'),
    ],
  ),
  platform(
    'platform_plans',
    'Plans',
    'Dynamic plans, pricing, limits and module bundles.',
    'Layers',
    3,
    [a('view', 'View plans'), a('create', 'Create plans'), a('update', 'Update plans'), a('archive', 'Archive plans')],
    [nav('plans', 'saas', 'Plans', '/admin/plans', ['platform_plans:view'], 3, 'Layers')],
  ),
  platform(
    'platform_payments',
    'Platform Payments',
    'Subscription payments collected from societies.',
    'Wallet',
    4,
    [a('view', 'View platform payments'), a('export', 'Export platform payments'), a('record', 'Record offline subscription payments')],
    [nav('payments', 'saas', 'Payments', '/admin/payments', ['platform_payments:view'], 4, 'Wallet')],
  ),
  platform(
    'platform_modules',
    'Modules',
    'Global module catalogue, status and navigation.',
    'Blocks',
    5,
    [a('view', 'View modules'), a('update', 'Update modules')],
    [nav('modules', 'product', 'Modules', '/admin/modules', ['platform_modules:view'], 0, 'Blocks')],
  ),
  platform(
    'platform_feature_flags',
    'Feature Flags',
    'Platform feature flags with society and plan rollouts.',
    'Flag',
    6,
    [a('view', 'View feature flags'), a('update', 'Update feature flags')],
    [nav('feature-flags', 'product', 'Feature Flags', '/admin/feature-flags', ['platform_feature_flags:view'], 1, 'Flag')],
  ),
  platform(
    'platform_landing',
    'Website CMS',
    'Landing page sections, pricing display, FAQs, testimonials, SEO and branding.',
    'Globe',
    7,
    [a('view', 'View website content'), a('update', 'Edit website content'), a('publish', 'Publish website content')],
    [
      nav('landing', 'website', 'Landing Page', '/admin/website/landing', ['platform_landing:view'], 0, 'Globe'),
      nav('pricing', 'website', 'Pricing', '/admin/website/pricing', ['platform_landing:view'], 1, 'Tag'),
      nav('faqs', 'website', 'FAQs', '/admin/website/faqs', ['platform_landing:view'], 2, 'CircleHelp'),
      nav('testimonials', 'website', 'Testimonials', '/admin/website/testimonials', ['platform_landing:view'], 3, 'Quote'),
      nav('seo', 'website', 'Brand & SEO', '/admin/website/settings', ['platform_landing:view'], 4, 'Search'),
    ],
  ),
  platform(
    'platform_leads',
    'Leads',
    'Demo requests, plan enquiries and sales pipeline.',
    'Handshake',
    8,
    [a('view', 'View leads'), a('update', 'Update leads'), a('assign', 'Assign leads'), a('delete', 'Delete leads'), a('export', 'Export leads'), a('convert', 'Convert leads to societies')],
    [nav('leads', 'customers', 'Leads', '/admin/leads', ['platform_leads:view'], 0, 'Handshake')],
  ),
  platform(
    'platform_support',
    'Support Inbox',
    'Unified support inbox for prospects, societies and members.',
    'LifeBuoy',
    9,
    [a('view', 'View tickets'), a('update', 'Update tickets'), a('assign', 'Assign tickets'), a('reply', 'Reply to tickets'), a('close', 'Close tickets')],
    [nav('support', 'customers', 'Support', '/admin/support', ['platform_support:view'], 1, 'LifeBuoy')],
  ),
  platform(
    'platform_analytics',
    'Analytics',
    'Platform growth, revenue and usage analytics.',
    'BarChart3',
    10,
    [a('view', 'View analytics'), a('export', 'Export analytics')],
    [nav('analytics', 'analytics', 'Reports', '/admin/analytics', ['platform_analytics:view'], 0, 'BarChart3')],
  ),
  platform(
    'platform_audit',
    'Audit Logs',
    'Platform-wide audit trail.',
    'ScrollText',
    11,
    [a('view', 'View audit logs'), a('export', 'Export audit logs')],
    [nav('audit', 'system', 'Audit Logs', '/admin/audit', ['platform_audit:view'], 0, 'ScrollText')],
  ),
  platform(
    'platform_settings',
    'Platform Settings',
    'Platform configuration, subscription rules, notification templates, integrations and platform users.',
    'Settings',
    12,
    [a('view', 'View platform settings'), a('update', 'Update platform settings'), a('manage_users', 'Manage platform users & roles'), a('view_health', 'View platform health')],
    [
      nav('settings', 'system', 'Settings', '/admin/settings', ['platform_settings:view'], 1, 'Settings'),
      nav('platform-users', 'system', 'Platform Users', '/admin/settings/users', ['platform_settings:manage_users'], 2, 'UserCog'),
      nav('health', 'system', 'Health', '/admin/settings/health', ['platform_settings:view_health'], 3, 'Activity'),
    ],
  ),
];
