import type { ModuleDefinition, ModuleActionDefinition, NavigationItemDefinition } from './types';

const a = (key: string, label: string, description?: string, ownScope = false): ModuleActionDefinition => ({
  key,
  label,
  description,
  ownScope,
});

const crud = (label: string): ModuleActionDefinition[] => [
  a('view', `View ${label}`),
  a('create', `Create ${label}`),
  a('update', `Update ${label}`),
  a('delete', `Delete ${label}`),
  a('export', `Export ${label}`),
];

const nav = (
  key: string,
  group: string,
  label: string,
  path: string,
  permissions: string[],
  sortOrder: number,
  audience: NavigationItemDefinition['audience'] = 'ADMIN',
  icon?: string,
): NavigationItemDefinition => ({ key, group, label, path, permissions, sortOrder, audience, icon });

const base = (
  key: string,
  name: string,
  description: string,
  icon: string,
  category: ModuleDefinition['category'],
  sortOrder: number,
  actions: ModuleActionDefinition[],
  navigation: NavigationItemDefinition[],
  opts: Partial<Pick<ModuleDefinition, 'isCore' | 'dependencies' | 'featureFlag' | 'configuration' | 'status'>> = {},
): ModuleDefinition => ({
  key,
  name,
  description,
  icon,
  category,
  scope: 'SOCIETY',
  isCore: opts.isCore ?? false,
  status: opts.status ?? 'ACTIVE',
  sortOrder,
  dependencies: opts.dependencies ?? [],
  actions,
  navigation,
  featureFlag: opts.featureFlag,
  version: '1.0.0',
  configuration: opts.configuration ?? {},
});

export const SOCIETY_MODULES: ModuleDefinition[] = [
  base(
    'dashboard',
    'Dashboard',
    'Society overview with permission-aware widgets.',
    'LayoutDashboard',
    'CORE',
    0,
    [a('view', 'View dashboard')],
    [
      nav('overview', 'overview', 'Overview', '/app', ['dashboard:view'], 0, 'ADMIN', 'LayoutDashboard'),
      nav('my-home', 'my', 'My Home', '/app/my', ['dashboard:view'], 0, 'MEMBER', 'Home'),
    ],
    { isCore: true },
  ),
  base(
    'society',
    'Society & Settings',
    'Society profile, configuration, modules, roles, users, categories and workflows.',
    'Settings',
    'CORE',
    1,
    [
      a('view', 'View society profile'),
      a('update', 'Update society profile'),
      a('manage_settings', 'Manage society settings'),
      a('manage_modules', 'Enable / disable modules'),
      a('manage_roles', 'Manage roles & permissions'),
      a('manage_users', 'Manage users & invitations'),
      a('manage_categories', 'Manage configurable categories'),
      a('manage_workflows', 'Manage approval workflows & SLA'),
      a('manage_notifications', 'Manage notification channels & templates'),
      a('import', 'Import data from spreadsheets'),
      a('handover', 'Run committee handover'),
      a('view_audit', 'View audit log'),
      a('view_subscription', 'View subscription & plan'),
      a('manage_subscription', 'Manage subscription & plan'),
    ],
    [
      nav('settings', 'settings', 'Settings', '/app/settings', ['society:view', 'society:manage_settings'], 0, 'ADMIN', 'Settings'),
      nav('modules', 'settings', 'Modules', '/app/settings/modules', ['society:manage_modules'], 1, 'ADMIN', 'Blocks'),
      nav('roles', 'settings', 'Roles & Permissions', '/app/settings/roles', ['society:manage_roles'], 2, 'ADMIN', 'ShieldCheck'),
      nav('users', 'settings', 'Users', '/app/settings/users', ['society:manage_users'], 3, 'ADMIN', 'Users'),
      nav('categories', 'settings', 'Categories', '/app/settings/categories', ['society:manage_categories'], 4, 'ADMIN', 'Tags'),
      nav('workflows', 'settings', 'Workflows & SLA', '/app/settings/workflows', ['society:manage_workflows'], 5, 'ADMIN', 'GitBranch'),
      nav('notification-settings', 'settings', 'Notifications', '/app/settings/notifications', ['society:manage_notifications'], 6, 'ADMIN', 'BellRing'),
      nav('subscription', 'settings', 'Subscription', '/app/settings/subscription', ['society:view_subscription'], 7, 'ADMIN', 'CreditCard'),
      nav('import', 'settings', 'Data Import', '/app/settings/import', ['society:import'], 8, 'ADMIN', 'Upload'),
      nav('handover', 'settings', 'Committee Handover', '/app/settings/handover', ['society:handover'], 9, 'ADMIN', 'ArrowLeftRight'),
      nav('approvals', 'overview', 'Approvals', '/app/approvals', ['expenses:approve', 'amenities:approve', 'society:manage_settings'], 1, 'ADMIN', 'Inbox'),
      nav('audit', 'settings', 'Audit Log', '/app/settings/audit', ['society:view_audit'], 10, 'ADMIN', 'ScrollText'),
    ],
    { isCore: true },
  ),
  base(
    'notifications',
    'Notifications',
    'In-app notification centre and delivery channels.',
    'Bell',
    'CORE',
    2,
    [a('view', 'View own notifications', undefined, true)],
    [],
    { isCore: true },
  ),
  // ---------------- COMMUNITY ----------------
  base(
    'units',
    'Units & Buildings',
    'Towers, wings, floors and units with owner/tenant mapping and unit ledger.',
    'Building2',
    'COMMUNITY',
    10,
    [...crud('units'), a('import', 'Import units'), a('manage_structure', 'Manage buildings / towers / wings')],
    [
      nav('units', 'community', 'Units', '/app/units', ['units:view'], 0, 'ADMIN', 'Building2'),
      nav('buildings', 'community', 'Buildings', '/app/buildings', ['units:manage_structure'], 1, 'ADMIN', 'Building'),
      nav('my-unit', 'my', 'My Unit', '/app/my/unit', ['residents:view_own'], 2, 'MEMBER', 'Home'),
    ],
  ),
  base(
    'residents',
    'Residents',
    'Owners, tenants, family members, move-in / move-out workflows and household access.',
    'Users',
    'COMMUNITY',
    11,
    [
      ...crud('residents'),
      a('import', 'Import residents'),
      a('move', 'Process move-in / move-out'),
      a('approve_move', 'Approve move requests'),
      a('lookup', 'Look up resident name & unit (directory / gate)'),
      a('view_own', 'View own household', undefined, true),
      a('manage_own', 'Manage own profile & family', undefined, true),
      a('view_contact', 'View resident phone & email'),
    ],
    [
      nav('residents', 'community', 'Residents', '/app/residents', ['residents:view'], 2, 'ADMIN', 'Users'),
      nav('moves', 'community', 'Move In / Out', '/app/residents/moves', ['residents:move', 'residents:approve_move'], 3, 'ADMIN', 'Truck'),
      nav('directory', 'community', 'Directory', '/app/directory', ['residents:lookup'], 4, 'ADMIN', 'BookUser'),
      nav('my-profile', 'my', 'My Profile', '/app/my/profile', ['residents:view_own'], 1, 'MEMBER', 'User'),
      nav('my-family', 'my', 'My Family', '/app/my/family', ['residents:view_own'], 3, 'MEMBER', 'HeartHandshake'),
    ],
    { dependencies: ['units'] },
  ),
  base(
    'vehicles',
    'Vehicles',
    'Resident vehicle registry with stickers and gate lookup.',
    'Car',
    'COMMUNITY',
    12,
    [
      ...crud('vehicles'),
      a('view_own', 'View own vehicles', undefined, true),
      a('create_own', 'Register own vehicles', undefined, true),
    ],
    [
      nav('vehicles', 'community', 'Vehicles', '/app/vehicles', ['vehicles:view'], 5, 'ADMIN', 'Car'),
      nav('my-vehicles', 'my', 'My Vehicles', '/app/my/vehicles', ['vehicles:view_own'], 8, 'MEMBER', 'Car'),
    ],
    { dependencies: ['units'] },
  ),
  base(
    'parking',
    'Parking',
    'Parking slots, allocation to units and vehicles.',
    'ParkingSquare',
    'COMMUNITY',
    13,
    [...crud('parking slots'), a('allocate', 'Allocate / release slots')],
    [nav('parking', 'community', 'Parking', '/app/parking', ['parking:view'], 6, 'ADMIN', 'ParkingSquare')],
    { dependencies: ['units'] },
  ),
  // ---------------- FINANCE ----------------
  base(
    'billing',
    'Billing',
    'Configurable charge heads, billing cycles, metered utilities and invoices.',
    'Receipt',
    'FINANCE',
    20,
    [
      ...crud('invoices'),
      a('issue', 'Issue invoices'),
      a('cancel', 'Cancel invoices'),
      a('generate', 'Run billing cycle'),
      a('configure', 'Configure billing (charge heads, cycle, penalties)'),
      a('meter_readings', 'Record meter readings'),
      a('view_own', 'View own bills', undefined, true),
    ],
    [
      nav('billing', 'finance', 'Billing', '/app/billing', ['billing:view'], 0, 'ADMIN', 'Receipt'),
      nav('billing-config', 'finance', 'Billing Setup', '/app/billing/setup', ['billing:configure'], 1, 'ADMIN', 'SlidersHorizontal'),
      nav('meters', 'finance', 'Meter Readings', '/app/billing/meters', ['billing:meter_readings'], 2, 'ADMIN', 'Gauge'),
      nav('my-bills', 'my', 'My Bills', '/app/my/bills', ['billing:view_own'], 4, 'MEMBER', 'Receipt'),
    ],
    { dependencies: ['units'] },
  ),
  base(
    'payments',
    'Payments',
    'Online and offline collections, receipts, refunds and reconciliation.',
    'Wallet',
    'FINANCE',
    21,
    [
      ...crud('payments'),
      a('refund', 'Refund payments'),
      a('reconcile', 'Reconcile payments'),
      a('configure', 'Configure payment gateway'),
      a('view_own', 'View own payments & receipts', undefined, true),
      a('pay_own', 'Pay own bills online', undefined, true),
    ],
    [
      nav('payments', 'finance', 'Payments', '/app/payments', ['payments:view'], 3, 'ADMIN', 'Wallet'),
      nav('my-payments', 'my', 'My Payments', '/app/my/payments', ['payments:view_own'], 5, 'MEMBER', 'Wallet'),
      nav('payment-gateway', 'settings', 'Payment gateway', '/app/settings/payments', ['payments:configure'], 6, 'ADMIN', 'CreditCard'),
    ],
    { dependencies: ['billing'] },
  ),
  base(
    'expenses',
    'Expenses',
    'Expense recording with configurable approval workflow and vendor payables.',
    'BadgeIndianRupee',
    'FINANCE',
    22,
    [...crud('expenses'), a('submit', 'Submit expenses for approval'), a('approve', 'Approve / reject expenses'), a('pay', 'Record expense payments')],
    [nav('expenses', 'finance', 'Expenses', '/app/expenses', ['expenses:view'], 4, 'ADMIN', 'BadgeIndianRupee'), nav('purchase-orders', 'finance', 'Purchase Orders', '/app/expenses/purchase-orders', ['expenses:view'], 9, 'ADMIN', 'ClipboardList')],
  ),
  base(
    'accounting',
    'Accounting',
    'Double-entry ledger, chart of accounts, funds, bank accounts and financial reports.',
    'BookOpenCheck',
    'FINANCE',
    23,
    [
      a('view', 'View ledgers & reports'),
      a('create', 'Create journal entries'),
      a('update', 'Update draft entries'),
      a('post', 'Post journal entries'),
      a('reverse', 'Reverse posted entries'),
      a('configure', 'Manage chart of accounts, funds & bank accounts'),
      a('reconcile', 'Bank reconciliation'),
      a('export', 'Export accounting reports'),
    ],
    [
      nav('accounting', 'finance', 'Accounting', '/app/accounting', ['accounting:view'], 5, 'ADMIN', 'BookOpenCheck'),
      nav('bank', 'finance', 'Bank & Reconciliation', '/app/accounting/bank', ['accounting:reconcile', 'accounting:configure'], 6, 'ADMIN', 'Landmark'),
      nav('journals', 'finance', 'Journals', '/app/accounting/journals', ['accounting:view'], 7, 'ADMIN', 'NotebookPen'),
      nav('chart-of-accounts', 'finance', 'Chart of Accounts', '/app/accounting/accounts', ['accounting:configure', 'accounting:view'], 8, 'ADMIN', 'ListTree'),
    ],
  ),
  // ---------------- OPERATIONS ----------------
  base(
    'complaints',
    'Helpdesk & Complaints',
    'Ticketing with categories, SLA, assignment, escalation and resolution.',
    'MessageSquareWarning',
    'OPERATIONS',
    30,
    [
      a('view', 'View all complaints'),
      a('create', 'Raise complaints'),
      a('update', 'Update complaints'),
      a('assign', 'Assign complaints'),
      a('resolve', 'Resolve complaints'),
      a('close', 'Close complaints'),
      a('comment', 'Comment on complaints'),
      a('configure', 'Configure categories, SLA & escalation'),
      a('export', 'Export complaints'),
      a('view_own', 'View own complaints', undefined, true),
    ],
    [
      nav('complaints', 'operations', 'Complaints', '/app/complaints', ['complaints:view'], 0, 'ADMIN', 'MessageSquareWarning'),
      nav('my-complaints', 'my', 'My Complaints', '/app/my/complaints', ['complaints:view_own'], 6, 'MEMBER', 'MessageSquareWarning'),
    ],
  ),
  base(
    'visitors',
    'Visitors & Gate',
    'Pre-approved passes, walk-ins, QR / passcode validation, check-in and check-out.',
    'DoorOpen',
    'OPERATIONS',
    31,
    [
      a('view', 'View all visitors'),
      a('create', 'Register walk-in visitors'),
      a('approve', 'Approve visitors'),
      a('deny', 'Deny visitors'),
      a('checkin', 'Check-in visitors'),
      a('checkout', 'Check-out visitors'),
      a('configure', 'Configure visitor categories & gates'),
      a('export', 'Export visitor log'),
      a('view_own', 'View own visitors', undefined, true),
      a('create_own', 'Pre-approve own visitors', undefined, true),
    ],
    [
      nav('visitors', 'operations', 'Visitors', '/app/visitors', ['visitors:view'], 1, 'ADMIN', 'DoorOpen'),
      nav('my-visitors', 'my', 'My Visitors', '/app/my/visitors', ['visitors:view_own'], 7, 'MEMBER', 'DoorOpen'),
      nav('gate-dashboard', 'gate', 'Gate', '/guard', ['visitors:checkin', 'visitors:checkout'], 0, 'GUARD', 'DoorOpen'),
      nav('gate-scan', 'gate', 'Scan Pass', '/guard/scan', ['visitors:checkin'], 1, 'GUARD', 'ScanLine'),
      nav('gate-walkin', 'gate', 'Walk-in', '/guard/walk-in', ['visitors:create'], 2, 'GUARD', 'UserPlus'),
      nav('gate-expected', 'gate', 'Expected', '/guard/expected', ['visitors:view'], 3, 'GUARD', 'CalendarClock'),
      nav('gate-timeline', 'gate', 'Timeline', '/guard/timeline', ['visitors:view'], 4, 'GUARD', 'History'),
    ],
    { dependencies: ['residents'], configuration: { passValidityHours: 24, passcodeLength: 6, dailyGuestCap: 0 } },
  ),
  base(
    'delivery',
    'Deliveries',
    'Courier, food and package tracking with leave-at-gate support.',
    'Package',
    'OPERATIONS',
    32,
    [
      a('view', 'View deliveries'),
      a('create', 'Log deliveries'),
      a('update', 'Update delivery status'),
      a('collect', 'Mark deliveries collected'),
      a('export', 'Export deliveries'),
      a('view_own', 'View own deliveries', undefined, true),
      a('create_own', 'Announce expected deliveries', undefined, true),
    ],
    [
      nav('deliveries', 'operations', 'Deliveries', '/app/deliveries', ['delivery:view'], 2, 'ADMIN', 'Package'),
      nav('my-deliveries', 'my', 'My Deliveries', '/app/my/deliveries', ['delivery:view_own'], 8, 'MEMBER', 'Package'),
      nav('gate-deliveries', 'gate', 'Deliveries', '/guard/deliveries', ['delivery:create'], 5, 'GUARD', 'Package'),
    ],
    { dependencies: ['residents'] },
  ),
  base(
    'security',
    'Security & Incidents',
    'Gates, guard shifts and incident reporting.',
    'Shield',
    'OPERATIONS',
    33,
    [
      a('view', 'View incidents'),
      a('create', 'Report incidents'),
      a('update', 'Update incidents'),
      a('resolve', 'Resolve incidents'),
      a('configure', 'Manage gates'),
      a('export', 'Export incidents'),
    ],
    [
      nav('security', 'operations', 'Security', '/app/security', ['security:view'], 3, 'ADMIN', 'Shield'),
      nav('gate-incidents', 'gate', 'Incidents', '/guard/incidents', ['security:create'], 6, 'GUARD', 'Siren'),
    ],
  ),
  base(
    'amenities',
    'Amenities',
    'Amenity catalogue, slot booking, approvals and cancellation policies.',
    'Dumbbell',
    'OPERATIONS',
    34,
    [
      ...crud('amenities'),
      a('book', 'Book amenities'),
      a('approve', 'Approve / reject bookings'),
      a('cancel', 'Cancel any booking'),
      a('view_bookings', 'View all bookings'),
      a('view_own', 'View own bookings', undefined, true),
    ],
    [
      nav('amenities', 'operations', 'Amenities', '/app/amenities', ['amenities:view_bookings', 'amenities:update'], 4, 'ADMIN', 'Dumbbell'),
      nav('my-amenities', 'my', 'My Amenities', '/app/my/amenities', ['amenities:book', 'amenities:view_own'], 9, 'MEMBER', 'Dumbbell'),
    ],
  ),
  base(
    'staff',
    'Staff',
    'Society staff, categories, shifts and attendance.',
    'HardHat',
    'OPERATIONS',
    35,
    [...crud('staff'), a('attendance', 'Mark & view attendance'), a('configure', 'Manage staff categories & shifts')],
    [nav('staff', 'operations', 'Staff', '/app/staff', ['staff:view'], 5, 'ADMIN', 'HardHat')],
  ),
  base(
    'domestic_help',
    'Domestic Help',
    'Maids, cooks, drivers and other household help with verification and gate entry.',
    'Sparkles',
    'OPERATIONS',
    36,
    [
      ...crud('domestic help'),
      a('verify', 'Verify domestic help'),
      a('view_own', 'View own domestic help', undefined, true),
      a('create_own', 'Register own domestic help', undefined, true),
    ],
    [
      nav('domestic-help', 'operations', 'Domestic Help', '/app/domestic-help', ['domestic_help:view'], 6, 'ADMIN', 'Sparkles'),
      nav('my-help', 'my', 'My Domestic Help', '/app/my/domestic-help', ['domestic_help:view_own'], 10, 'MEMBER', 'Sparkles'),
      nav('gate-help', 'gate', 'Help & vehicles', '/guard/help', ['domestic_help:view'], 5, 'GUARD', 'Sparkles'),
    ],
    { dependencies: ['residents'] },
  ),
  base(
    'vendors',
    'Vendors',
    'Vendor directory, categories, ratings and documents.',
    'Store',
    'OPERATIONS',
    37,
    [...crud('vendors'), a('configure', 'Manage vendor categories')],
    [nav('vendors', 'operations', 'Vendors', '/app/vendors', ['vendors:view'], 7, 'ADMIN', 'Store')],
  ),
  base(
    'contracts',
    'Contracts & AMC',
    'Vendor contracts, AMCs, renewals and expiry reminders.',
    'FileSignature',
    'OPERATIONS',
    38,
    [...crud('contracts'), a('renew', 'Renew contracts')],
    [nav('contracts', 'operations', 'Contracts & AMC', '/app/contracts', ['contracts:view'], 8, 'ADMIN', 'FileSignature')],
    { dependencies: ['vendors'], configuration: { reminderDays: [30, 15, 7, 1] } },
  ),
  base(
    'assets',
    'Assets',
    'Asset register with lifecycle, warranty and maintenance log.',
    'Boxes',
    'OPERATIONS',
    39,
    [...crud('assets'), a('maintain', 'Log maintenance & change lifecycle status')],
    [nav('assets', 'operations', 'Assets', '/app/assets', ['assets:view'], 9, 'ADMIN', 'Boxes')],
  ),
  base(
    'inventory',
    'Inventory',
    'Stock items, stock in/out and low-stock alerts.',
    'Warehouse',
    'OPERATIONS',
    40,
    [...crud('inventory items'), a('transact', 'Record stock in / out')],
    [nav('inventory', 'operations', 'Inventory', '/app/inventory', ['inventory:view'], 10, 'ADMIN', 'Warehouse')],
  ),
  // ---------------- COMMUNICATION ----------------
  base(
    'notices',
    'Notices',
    'Targeted notices with audiences, scheduling and archive.',
    'Megaphone',
    'COMMUNICATION',
    50,
    [a('view', 'View notices'), a('create', 'Create notices'), a('update', 'Update notices'), a('delete', 'Delete notices'), a('publish', 'Publish / archive notices')],
    [
      nav('notices', 'communication', 'Notices', '/app/notices', ['notices:create', 'notices:publish'], 0, 'ADMIN', 'Megaphone'),
      nav('my-notices', 'my', 'Notices', '/app/my/notices', ['notices:view'], 11, 'MEMBER', 'Megaphone'),
    ],
  ),
  base(
    'communication',
    'Community',
    'Community posts, discussions and announcements.',
    'MessagesSquare',
    'COMMUNICATION',
    51,
    [a('view', 'View community feed'), a('create', 'Post to community'), a('moderate', 'Moderate posts'), a('announce', 'Publish announcements')],
    [
      nav('community', 'communication', 'Community Feed', '/app/community', ['communication:moderate', 'communication:announce'], 1, 'ADMIN', 'MessagesSquare'),
      nav('my-community', 'my', 'Community', '/app/my/community', ['communication:view'], 12, 'MEMBER', 'MessagesSquare'),
    ],
  ),
  base(
    'events',
    'Events',
    'Community events, AGM notices and RSVP tracking.',
    'CalendarDays',
    'COMMUNICATION',
    52,
    [...crud('events'), a('rsvp', 'RSVP to events')],
    [
      nav('events', 'communication', 'Events', '/app/events', ['events:create', 'events:update'], 2, 'ADMIN', 'CalendarDays'),
      nav('my-events', 'my', 'Events', '/app/my/events', ['events:view'], 13, 'MEMBER', 'CalendarDays'),
    ],
  ),
  base(
    'polls',
    'Polls',
    'Quick polls with audiences, anonymity and one vote per user.',
    'Vote',
    'COMMUNICATION',
    53,
    [...crud('polls'), a('vote', 'Vote in polls'), a('results', 'View poll results')],
    [
      nav('polls', 'communication', 'Polls', '/app/polls', ['polls:create', 'polls:results'], 3, 'ADMIN', 'Vote'),
      nav('my-polls', 'my', 'Polls', '/app/my/polls', ['polls:view'], 14, 'MEMBER', 'Vote'),
    ],
  ),
  base(
    'surveys',
    'Surveys',
    'Multi-question surveys with responses and exports.',
    'ClipboardList',
    'COMMUNICATION',
    54,
    [...crud('surveys'), a('respond', 'Respond to surveys'), a('results', 'View survey results')],
    [
      nav('surveys', 'communication', 'Surveys', '/app/surveys', ['surveys:create', 'surveys:results'], 4, 'ADMIN', 'ClipboardList'),
      nav('my-surveys', 'my', 'Surveys', '/app/my/surveys', ['surveys:view'], 15, 'MEMBER', 'ClipboardList'),
    ],
  ),
  // ---------------- GOVERNANCE ----------------
  base(
    'meetings',
    'Meetings & AGM',
    'Meeting scheduling, agenda, participants, minutes and resolutions.',
    'Presentation',
    'GOVERNANCE',
    60,
    [...crud('meetings'), a('minutes', 'Record minutes & resolutions')],
    [
      nav('meetings', 'governance', 'Meetings', '/app/meetings', ['meetings:view'], 0, 'ADMIN', 'Presentation'),
      nav('agm', 'governance', 'AGM', '/app/meetings?type=AGM', ['meetings:view'], 1, 'ADMIN', 'Landmark'),
      nav('my-meetings', 'my', 'Meetings', '/app/my/meetings', ['meetings:view'], 16, 'MEMBER', 'Presentation'),
    ],
  ),
  base(
    'voting',
    'Voting & Elections',
    'Resolution voting and committee elections with one vote per unit or user.',
    'CheckSquare',
    'GOVERNANCE',
    61,
    [...crud('votings'), a('vote', 'Cast votes'), a('results', 'View results'), a('close', 'Open / close voting')],
    [
      nav('voting', 'governance', 'Voting', '/app/voting', ['voting:create', 'voting:results'], 2, 'ADMIN', 'CheckSquare'),
      nav('my-voting', 'my', 'Voting', '/app/my/voting', ['voting:view'], 17, 'MEMBER', 'CheckSquare'),
    ],
  ),
  base(
    'governance',
    'Committee',
    'Committee composition, positions and terms.',
    'Landmark',
    'GOVERNANCE',
    62,
    [a('view', 'View committee'), a('manage', 'Manage committee')],
    [nav('committee', 'governance', 'Committee', '/app/committee', ['governance:view'], 3, 'ADMIN', 'Landmark')],
  ),
  base(
    'documents',
    'Documents',
    'Document repository with folders, tags, versions, expiry and signed downloads.',
    'FolderOpen',
    'GOVERNANCE',
    63,
    [
      a('view', 'View documents'),
      a('create', 'Upload documents'),
      a('update', 'Update documents'),
      a('delete', 'Delete documents'),
      a('download', 'Download documents'),
      a('archive', 'Archive documents'),
      a('manage_folders', 'Manage folders'),
      a('view_own', 'View own / shared documents', undefined, true),
    ],
    [
      nav('documents', 'governance', 'Documents', '/app/documents', ['documents:view'], 4, 'ADMIN', 'FolderOpen'),
      nav('my-documents', 'my', 'My Documents', '/app/my/documents', ['documents:view_own'], 18, 'MEMBER', 'FolderOpen'),
    ],
  ),
  // ---------------- REPORTS / SUPPORT / EMERGENCY ----------------
  base(
    'reports',
    'Reports',
    'Operational and financial reports with separate export permission.',
    'BarChart3',
    'REPORTS',
    70,
    [a('view', 'View reports'), a('export', 'Export reports')],
    [nav('reports', 'reports', 'Reports', '/app/reports', ['reports:view'], 0, 'ADMIN', 'BarChart3')],
  ),
  base(
    'emergency',
    'Emergency',
    'Emergency contacts, SOS alerts and emergency announcements.',
    'Siren',
    'OPERATIONS',
    41,
    [a('view', 'View emergency contacts & alerts'), a('sos', 'Raise SOS'), a('manage', 'Manage emergency contacts'), a('respond', 'Acknowledge & resolve alerts'), a('broadcast', 'Send emergency announcement')],
    [
      nav('emergency', 'operations', 'Emergency', '/app/emergency', ['emergency:manage', 'emergency:respond'], 11, 'ADMIN', 'Siren'),
      nav('my-emergency', 'my', 'Emergency', '/app/my/emergency', ['emergency:view'], 19, 'MEMBER', 'Siren'),
      nav('gate-emergency', 'gate', 'Emergency', '/guard/emergency', ['emergency:view'], 7, 'GUARD', 'Siren'),
    ],
    { featureFlag: 'emergency_module' },
  ),
  base(
    'support',
    'Support',
    'Raise and track support tickets with the platform team.',
    'LifeBuoy',
    'SUPPORT',
    80,
    [a('create', 'Raise support tickets'), a('view_own', 'View own tickets', undefined, true), a('view', 'View all society tickets')],
    [
      nav('support', 'support', 'Support', '/app/support', ['support:view', 'support:create'], 0, 'ADMIN', 'LifeBuoy'),
      nav('my-support', 'my', 'Support', '/app/my/support', ['support:create'], 20, 'MEMBER', 'LifeBuoy'),
    ],
    { isCore: true },
  ),
];
