import type { NotificationChannel } from '@society-erp/shared';

export interface TemplateDefault {
  key: string;
  channel: NotificationChannel;
  subject?: string;
  body: string;
  description: string;
  variables: string[];
}

const both = (key: string, description: string, variables: string[], inApp: { title: string; body: string }, email?: { subject: string; body: string }, whatsapp?: string): TemplateDefault[] => {
  const out: TemplateDefault[] = [{ key, channel: 'IN_APP', subject: inApp.title, body: inApp.body, description, variables }];
  if (email) out.push({ key, channel: 'EMAIL', subject: email.subject, body: email.body, description, variables });
  if (whatsapp) out.push({ key, channel: 'WHATSAPP', body: whatsapp, description, variables });
  out.push({ key, channel: 'PUSH', subject: inApp.title, body: inApp.body, description, variables });
  return out;
};

/** Platform-level defaults; societies can override any template from Settings → Notifications. */
export const DEFAULT_NOTIFICATION_TEMPLATES: TemplateDefault[] = [
  {
    key: 'auth.password_reset',
    channel: 'EMAIL',
    subject: 'Reset your {{brandName}} password',
    body: '<p>Hi {{name}},</p><p>We received a request to reset your password. This link is valid for {{expiresInMinutes}} minutes.</p><p><a href="{{resetUrl}}">Reset password</a></p><p>If you did not request this, you can ignore this email.</p>',
    description: 'Password reset email',
    variables: ['name', 'resetUrl', 'expiresInMinutes', 'brandName'],
  },
  {
    key: 'user.invited',
    channel: 'EMAIL',
    subject: '{{inviterName}} invited you to {{societyName}} on {{brandName}}',
    body: '<p>Hi {{name}},</p><p>{{inviterName}} has invited you to join <strong>{{societyName}}</strong> as {{roles}}.</p><p><a href="{{inviteUrl}}">Accept invitation</a> (valid until {{expiresAt}})</p>{{#message}}<p>Message: {{message}}</p>{{/message}}',
    description: 'User invitation email',
    variables: ['name', 'inviterName', 'societyName', 'roles', 'inviteUrl', 'expiresAt', 'message', 'brandName'],
  },
  {
    key: 'society.welcome',
    channel: 'EMAIL',
    subject: 'Welcome to {{brandName}}, {{societyName}} is ready',
    body: '<p>Hi {{name}},</p><p>Your society <strong>{{societyName}}</strong> has been created on the {{planName}} plan. Your trial runs until {{trialEndDate}}.</p><p><a href="{{appUrl}}/app">Open your workspace</a> and finish the setup wizard.</p>',
    description: 'Welcome email after signup',
    variables: ['name', 'societyName', 'planName', 'trialEndDate', 'appUrl', 'brandName'],
  },
  ...both('subscription.expiring', 'Subscription expiring reminder', ['societyName', 'daysRemaining', 'renewalDate', 'planName'],
    { title: 'Subscription expiring in {{daysRemaining}} days', body: 'The {{planName}} subscription for {{societyName}} renews on {{renewalDate}}. Renew now to avoid interruption.' },
    { subject: '{{societyName}}: subscription expires in {{daysRemaining}} days', body: '<p>The {{planName}} subscription for <strong>{{societyName}}</strong> expires on {{renewalDate}}.</p><p>Please renew to keep uninterrupted access.</p>' },
    'Reminder: {{societyName}} subscription ({{planName}}) expires on {{renewalDate}}. Renew to avoid interruption.'),
  ...both('subscription.expired', 'Subscription expired', ['societyName', 'planName'],
    { title: 'Subscription expired', body: 'Access to {{societyName}} is blocked until the subscription is renewed.' },
    { subject: '{{societyName}}: subscription expired', body: '<p>The {{planName}} subscription for <strong>{{societyName}}</strong> has expired. Renew to restore access.</p>' }),
  ...both('subscription.past_due', 'Subscription past due', ['societyName', 'gracePeriodEndsAt'],
    { title: 'Payment overdue', body: 'The subscription for {{societyName}} is past due. Full access resumes after payment (grace period ends {{gracePeriodEndsAt}}).' },
    { subject: '{{societyName}}: subscription payment overdue', body: '<p>The subscription for <strong>{{societyName}}</strong> is past due. Please pay before {{gracePeriodEndsAt}} to keep access.</p>' }),
  ...both('subscription.activated', 'Subscription activated', ['societyName', 'planName', 'renewalDate'],
    { title: 'Subscription active', body: '{{societyName}} is now on the {{planName}} plan until {{renewalDate}}.' },
    { subject: '{{societyName}}: subscription activated', body: '<p>Thank you! <strong>{{societyName}}</strong> is on the {{planName}} plan until {{renewalDate}}.</p>' }),
  ...both('invoice.created', 'Invoice issued', ['invoiceNumber', 'unitCode', 'amount', 'dueDate', 'societyName'],
    { title: 'New invoice {{invoiceNumber}}', body: 'Invoice {{invoiceNumber}} for unit {{unitCode}}: {{amount}} due by {{dueDate}}.' },
    { subject: '{{societyName}}: invoice {{invoiceNumber}} for unit {{unitCode}}', body: '<p>Invoice <strong>{{invoiceNumber}}</strong> of {{amount}} has been issued for unit {{unitCode}}. Due date: {{dueDate}}.</p>' },
    '{{societyName}}: invoice {{invoiceNumber}} of {{amount}} for unit {{unitCode}} is due by {{dueDate}}.'),
  ...both('invoice.overdue', 'Invoice overdue', ['invoiceNumber', 'unitCode', 'balanceDue', 'dueDate'],
    { title: 'Invoice {{invoiceNumber}} overdue', body: '{{balanceDue}} is pending for unit {{unitCode}} since {{dueDate}}.' },
    { subject: 'Overdue: invoice {{invoiceNumber}}', body: '<p>Invoice {{invoiceNumber}} for unit {{unitCode}} is overdue. Balance due: {{balanceDue}}.</p>' },
    'Reminder: invoice {{invoiceNumber}} ({{balanceDue}}) for unit {{unitCode}} is overdue.'),
  ...both('payment.received', 'Payment received', ['receiptNumber', 'amount', 'unitCode', 'method'],
    { title: 'Payment received', body: 'Receipt {{receiptNumber}}: {{amount}} received for unit {{unitCode}} via {{method}}.' },
    { subject: 'Receipt {{receiptNumber}} - payment received', body: '<p>We received {{amount}} for unit {{unitCode}} via {{method}}. Receipt number: <strong>{{receiptNumber}}</strong>.</p>' },
    'Payment of {{amount}} received for unit {{unitCode}}. Receipt {{receiptNumber}}.'),
  ...both('complaint.created', 'Complaint raised', ['ticketNumber', 'title', 'unitCode', 'priority'],
    { title: 'New complaint {{ticketNumber}}', body: '{{title}} ({{priority}}) raised for unit {{unitCode}}.' },
    { subject: 'New complaint {{ticketNumber}}: {{title}}', body: '<p>A new {{priority}} complaint was raised for unit {{unitCode}}: <strong>{{title}}</strong>.</p>' }),
  ...both('complaint.assigned', 'Complaint assigned', ['ticketNumber', 'title', 'assigneeName'],
    { title: 'Complaint {{ticketNumber}} assigned', body: '{{title}} has been assigned to {{assigneeName}}.' }),
  ...both('complaint.updated', 'Complaint status updated', ['ticketNumber', 'title', 'status'],
    { title: 'Complaint {{ticketNumber}} {{status}}', body: '{{title}} is now {{status}}.' },
    { subject: 'Complaint {{ticketNumber}} is {{status}}', body: '<p>Your complaint <strong>{{title}}</strong> ({{ticketNumber}}) is now {{status}}.</p>' },
    'Complaint {{ticketNumber}} "{{title}}" is now {{status}}.'),
  ...both('complaint.escalated', 'Complaint escalated', ['ticketNumber', 'title', 'level'],
    { title: 'Complaint {{ticketNumber}} escalated (L{{level}})', body: 'SLA breached for "{{title}}". Escalated to level {{level}}.' },
    { subject: 'SLA breach: complaint {{ticketNumber}} escalated', body: '<p>Complaint <strong>{{title}}</strong> ({{ticketNumber}}) breached its SLA and was escalated to level {{level}}.</p>' }),
  ...both('visitor.pending', 'Walk-in visitor awaiting approval', ['visitorName', 'category', 'gate'],
    { title: 'Visitor at the gate', body: '{{visitorName}} ({{category}}) is waiting at {{gate}}. Approve or deny.' }, undefined,
    'Visitor {{visitorName}} ({{category}}) is waiting at {{gate}}. Open the app to approve or deny.'),
  ...both('visitor.approved', 'Visitor approved', ['visitorName'], { title: 'Visitor approved', body: '{{visitorName}} was approved for entry.' }),
  ...both('visitor.denied', 'Visitor denied', ['visitorName'], { title: 'Visitor denied', body: 'Entry for {{visitorName}} was denied.' }),
  ...both('visitor.pass_created', 'Visitor pass created', ['visitorName', 'passcode', 'validUntil', 'societyName'],
    { title: 'Pass ready for {{visitorName}}', body: 'Share passcode {{passcode}} (valid until {{validUntil}}).' }, undefined,
    'Your visitor pass for {{societyName}}: passcode {{passcode}}, valid until {{validUntil}}. Show it at the gate.'),
  ...both('visitor.checked_in', 'Visitor checked in', ['visitorName', 'time'], { title: '{{visitorName}} checked in', body: 'Checked in at {{time}}.' }),
  ...both('visitor.checked_out', 'Visitor checked out', ['visitorName', 'time'], { title: '{{visitorName}} checked out', body: 'Checked out at {{time}}.' }),
  ...both('delivery.arrived', 'Delivery at gate', ['provider', 'unitCode'], { title: 'Delivery at the gate', body: 'A {{provider}} delivery for unit {{unitCode}} has arrived.' }),
  ...both('notice.published', 'Notice published', ['title', 'societyName'],
    { title: 'Notice: {{title}}', body: 'A new notice has been published by {{societyName}}.' },
    { subject: '{{societyName}} notice: {{title}}', body: '<p>A new notice has been published: <strong>{{title}}</strong>.</p><p>{{excerpt}}</p>' },
    '{{societyName}} notice: {{title}}'),
  ...both('amenity.booking_confirmed', 'Amenity booking confirmed', ['amenityName', 'startAt'], { title: 'Booking confirmed', body: '{{amenityName}} is booked for {{startAt}}.' }),
  ...both('amenity.booking_pending', 'Amenity booking pending approval', ['amenityName', 'unitCode', 'startAt'], { title: 'Booking approval needed', body: 'Unit {{unitCode}} requested {{amenityName}} on {{startAt}}.' }),
  ...both('amenity.booking_rejected', 'Amenity booking rejected', ['amenityName', 'startAt', 'reason'], { title: 'Booking rejected', body: '{{amenityName}} on {{startAt}} was rejected. {{reason}}' }),
  ...both('amenity.payment_due', 'Amenity booking payment due', ['amenityName', 'amount', 'deadline', 'bookingNumber'],
    { title: 'Pay to confirm {{amenityName}}', body: 'Booking {{bookingNumber}}: pay {{amount}} before {{deadline}} to keep your slot.' }, undefined,
    'Your {{amenityName}} booking {{bookingNumber}} is approved. Pay {{amount}} before {{deadline}} to confirm it.'),
  ...both('amenity.booking_cancelled', 'Amenity booking cancelled', ['amenityName', 'startAt', 'bookingNumber', 'reason'],
    { title: 'Booking {{bookingNumber}} cancelled', body: '{{amenityName}} on {{startAt}} was cancelled. {{reason}}' }),
  ...both('amenity.refund_due', 'Amenity refund to process', ['bookingNumber', 'amount', 'unitCode', 'amenityName'],
    { title: 'Refund due: {{amount}}', body: 'Booking {{bookingNumber}} ({{amenityName}}, unit {{unitCode}}) has a refund of {{amount}} waiting to be processed.' }),
  ...both('community.announcement', 'Community announcement', ['title', 'excerpt', 'societyName'],
    { title: '{{title}}', body: '{{excerpt}}' },
    { subject: '{{societyName}}: {{title}}', body: '<p><strong>{{title}}</strong></p><p>{{excerpt}}</p>' },
    '{{societyName}}: {{title}} - {{excerpt}}'),
  ...both('community.commented', 'New comment on your post', ['name', 'excerpt'], { title: '{{name}} commented on your post', body: '{{excerpt}}' }),
  ...both('community.reported', 'Post reported', ['name', 'reason'], { title: 'A post was reported', body: '{{name}} reported a post: {{reason}}' }),
  ...both('event.cancelled', 'Event cancelled', ['name', 'startAt', 'reason'], { title: 'Cancelled: {{name}}', body: 'The event on {{startAt}} has been cancelled. {{reason}}' }, undefined, 'Cancelled: {{name}} on {{startAt}}. {{reason}}'),
  ...both('event.reminder', 'Event reminder', ['name', 'startAt', 'venue'], { title: 'Reminder: {{name}}', body: 'Starts {{startAt}} at {{venue}}.' }, undefined, 'Reminder: {{name}} starts {{startAt}} at {{venue}}.'),
  ...both('survey.opened', 'Survey opened', ['title', 'endAt'], { title: 'Survey: {{title}}', body: 'Share your views before {{endAt}}.' }),
  ...both('document.review_requested', 'Document awaiting review', ['title', 'name'], { title: 'Document to review: {{title}}', body: '{{name}} was uploaded and waits for your approval before residents can see it.' }),
  ...both('document.reviewed', 'Document reviewed', ['title', 'status', 'note'], { title: 'Document {{status}}: {{title}}', body: '{{note}}' }),
  ...both('document.expiring', 'Document expiring', ['title', 'expiresAt', 'daysRemaining'], { title: 'Expiring: {{title}}', body: '{{title}} expires on {{expiresAt}} ({{daysRemaining}} days).' }),
  ...both('meeting.reminder', 'Meeting reminder', ['title', 'scheduledAt', 'venue'], { title: 'Reminder: {{title}}', body: 'Starts {{scheduledAt}}{{#venue}} at {{venue}}{{/venue}}.' }, undefined, 'Reminder: {{title}} starts {{scheduledAt}} {{venue}}.'),
  ...both('meeting.cancelled', 'Meeting cancelled', ['title', 'scheduledAt', 'reason'], { title: 'Cancelled: {{title}}', body: 'The meeting on {{scheduledAt}} was cancelled. {{reason}}' }),
  ...both('meeting.minutes_published', 'Minutes published', ['title'], { title: 'Minutes: {{title}}', body: 'The minutes and resolutions are now available in the app.' }),
  ...both('voting.closed', 'Voting closed', ['title', 'outcome'], { title: 'Result: {{title}}', body: 'The vote closed: {{outcome}}.' }),
  ...both('committee.handover', 'Committee handover', ['status', 'note'], { title: 'Committee handover {{status}}', body: '{{note}}' }),
  ...both('domestic_help.registered', 'Domestic help registered', ['name', 'unitCode'], { title: 'New domestic help to verify', body: '{{name}} was registered by unit {{unitCode}}.' }),
  ...both('domestic_help.verified', 'Domestic help verification', ['name', 'status'], { title: '{{name}} {{status}}', body: 'The society office has {{status}} {{name}}.' }),
  ...both('domestic_help.entry', 'Domestic help at the gate', ['name', 'time', 'direction'], { title: '{{name}} {{direction}} at {{time}}', body: 'Your domestic help {{name}} {{direction}} the society at {{time}}.' }),
  ...both('expense.approval_requested', 'Expense approval requested', ['expenseNumber', 'amount', 'vendorName'], { title: 'Approval needed: {{expenseNumber}}', body: 'Expense of {{amount}} ({{vendorName}}) awaits your approval.' }),
  ...both('expense.decided', 'Expense approval decided', ['expenseNumber', 'decision'], { title: 'Expense {{expenseNumber}} {{decision}}', body: 'The expense was {{decision}}.' }),
  ...both('support.ticket.created', 'Support ticket created', ['ticketNumber', 'subject'],
    { title: 'Ticket {{ticketNumber}} created', body: '{{subject}}' },
    { subject: 'We received your request ({{ticketNumber}})', body: '<p>Thanks for contacting us. Your ticket <strong>{{ticketNumber}}</strong> "{{subject}}" has been created. We will reply shortly.</p>' }),
  ...both('support.ticket.replied', 'Support ticket reply', ['ticketNumber', 'subject', 'excerpt'],
    { title: 'Reply on ticket {{ticketNumber}}', body: '{{excerpt}}' },
    { subject: 'New reply on ticket {{ticketNumber}}: {{subject}}', body: '<p>There is a new reply on your ticket <strong>{{ticketNumber}}</strong>:</p><blockquote>{{excerpt}}</blockquote>' }),
  ...both('emergency.sos', 'SOS alert', ['raisedBy', 'unitCode', 'location'],
    { title: 'SOS from {{raisedBy}}', body: 'Emergency reported at {{location}} (unit {{unitCode}}). Respond immediately.' }, undefined,
    'SOS: {{raisedBy}} reported an emergency at {{location}} (unit {{unitCode}}).'),
  ...both('emergency.broadcast', 'Emergency announcement', ['title', 'message'],
    { title: 'EMERGENCY: {{title}}', body: '{{message}}' },
    { subject: 'EMERGENCY: {{title}}', body: '<p><strong>{{title}}</strong></p><p>{{message}}</p>' },
    'EMERGENCY: {{title}} - {{message}}'),
  ...both('emergency.acknowledged', 'SOS acknowledged', ['responder', 'alertNumber'], { title: 'Help is on the way', body: '{{responder}} has acknowledged your SOS ({{alertNumber}}) and is responding.' }, undefined, 'Help is on the way: {{responder}} acknowledged your SOS {{alertNumber}}.'),
  ...both('emergency.resolved', 'SOS resolved', ['alertNumber', 'outcome', 'by'], { title: 'SOS {{alertNumber}} {{outcome}}', body: 'The alert was {{outcome}} by {{by}}.' }),
  ...both('emergency.all_clear', 'Emergency all clear', ['title', 'note'], { title: 'All clear: {{title}}', body: '{{note}}' }, { subject: 'All clear: {{title}}', body: '<p><strong>All clear: {{title}}</strong></p><p>{{note}}</p>' }, 'ALL CLEAR: {{title}} - {{note}}'),
  ...both('emergency.escalated', 'SOS not acknowledged', ['alertNumber', 'raisedBy', 'unitCode', 'minutes', 'location'], { title: 'Unanswered SOS {{alertNumber}}', body: 'SOS from {{raisedBy}} (unit {{unitCode}}) at {{location}} has had no response for {{minutes}} minutes.' }, undefined, 'URGENT: SOS {{alertNumber}} from {{raisedBy}} at {{location}} unanswered for {{minutes}} minutes.'),
  ...both('incident.reported', 'Incident reported', ['incidentNumber', 'title', 'severity', 'typeKey', 'location'], { title: 'Incident {{incidentNumber}}: {{title}}', body: '{{severity}} {{typeKey}} at {{location}}.' }),
  ...both('incident.unit_notice', 'Incident involving your unit', ['incidentNumber', 'title', 'location'], { title: 'Security incident logged: {{title}}', body: 'Incident {{incidentNumber}} at {{location}} mentions your unit. The security team is on it.' }),
  ...both('incident.assigned', 'Incident assigned', ['incidentNumber', 'title'], { title: 'Assigned to you: {{incidentNumber}}', body: '{{title}}' }),
  ...both('incident.updated', 'Incident updated', ['incidentNumber', 'title', 'status', 'change'], { title: 'Incident {{incidentNumber}} {{status}}', body: '{{title}}' }),
  ...both('contract.expiring', 'Contract expiring', ['title', 'vendorName', 'endDate', 'daysRemaining'], { title: 'Contract expiring: {{title}}', body: '{{vendorName}} contract ends on {{endDate}} ({{daysRemaining}} days).' }),
  ...both('contract.expired', 'Contract expired', ['title', 'vendorName', 'endDate'], { title: 'Contract expired: {{title}}', body: '{{vendorName}} contract ended on {{endDate}}. Renew or terminate it.' }),
  ...both('contract.visit_due', 'AMC visit due', ['title', 'vendorName', 'dueDate'], { title: 'AMC visit due: {{title}}', body: '{{vendorName}} service visit is due by {{dueDate}}.' }),
  ...both('asset.maintenance_due', 'Asset maintenance due', ['name', 'assetCode', 'dueDate', 'location'], { title: 'Maintenance due: {{name}}', body: '{{assetCode}} at {{location}} is due for maintenance by {{dueDate}}.' }),
  ...both('asset.warranty_expiring', 'Asset warranty expiring', ['name', 'assetCode', 'warrantyUntil'], { title: 'Warranty ending: {{name}}', body: '{{assetCode}} warranty ends on {{warrantyUntil}}. Get pending issues fixed before then.' }),
  ...both('inventory.low_stock', 'Low stock alert', ['itemName', 'currentStock', 'minimumLevel'], { title: 'Low stock: {{itemName}}', body: 'Only {{currentStock}} left (minimum {{minimumLevel}}).' }),
  ...both('event.created', 'Event announced', ['name', 'startAt'], { title: 'Event: {{name}}', body: 'Scheduled for {{startAt}}. RSVP in the app.' }),
  ...both('poll.created', 'Poll opened', ['question'], { title: 'New poll', body: '{{question}}' }),
  ...both('meeting.scheduled', 'Meeting scheduled', ['title', 'scheduledAt', 'venue'], { title: 'Meeting: {{title}}', body: '{{scheduledAt}} at {{venue}}.' }),
  ...both('voting.opened', 'Voting opened', ['title', 'endAt'], { title: 'Voting open: {{title}}', body: 'Cast your vote before {{endAt}}.' }),
  ...both('move.requested', 'Move request', ['type', 'unitCode', 'residentName'], { title: '{{type}} request for {{unitCode}}', body: '{{residentName}} - awaiting approval.' }),
  ...both('user.joined', 'User joined society', ['name', 'societyName'], { title: '{{name}} joined', body: '{{name}} accepted the invitation to {{societyName}}.' }),
  ...both('lead.created', 'New lead', ['name', 'type', 'societyName'], { title: 'New lead: {{name}}', body: '{{type}} from {{societyName}}.' }),
  ...both('society.created', 'New society signup', ['societyName', 'planName'], { title: 'New signup: {{societyName}}', body: 'Started on the {{planName}} plan.' }),
  ...both('import.completed', 'Import completed', ['type', 'imported', 'failed'], { title: 'Import finished: {{type}}', body: '{{imported}} rows imported, {{failed}} failed.' }),
  ...both('staff.attendance_missing', 'Attendance missing', ['date', 'count'], { title: 'Attendance not marked', body: '{{count}} staff have no attendance for {{date}}.' }),
];
